name: Generate Specs

on:
    push:
        paths:
            - "requirements.csv"
            - "structure.csv"
    workflow_dispatch:
permissions:
    contents: write

jobs:
    build-specs:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Generate Specifications
              uses: hugoglvs/pegs-specs-custom-action@v1.1
              with:
                  requirements-path: "requirements.csv"
                  output-dir: "docs/build"
                  structure-path: "structure.csv"
                  project-name: "MacOS Clipboard Manager Specifications"
                  authors: "Hugo Goncalves, Lea Poisson"
                  #   logo-path: "assets/image.svg"

            - name: Upload Artifacts
              uses: actions/upload-artifact@v4
              with:
                  name: specifications
                  path: docs/build/*.pdf
